---
  - name: Setup Mysql
    hosts: postgres
    become: true
    become_method: sudo


    tasks:
    vars_files:
      -  vars/main.yaml
      
    roles:
      - { role: geerlingguy.postgresql }

        