name: assessment-pipe
on:
  push:
    branches:
      - submission

jobs:
  containerize:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        working-directory: /app/
        run: |
          docker build . -t 4568910/devops-assessment
          docker tag 4568910/devops-assessment:latest 4568910/devops-assessment:"v${GITHUB_RUN_NUMBER}"

      

      - name: Push Docker image
        run: docker push 4568910/devops-assessment:"v${GITHUB_RUN_NUMBER}"

      