name: CI workflow
on:
  workflow_dispatch
    
  # push:
  #   branches:
  #     - dev

jobs:
  containerize:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image and save a previous version
        working-directory: app
        run: |
          docker build . -t 4568910/devops-assessment:latest
          docker tag 4568910/devops-assessment:latest 4568910/devops-assessment:latest-2

          docker pull 4568910/devops-assessment:latest
          docker tag 4568910/devops-assessment:latest 4568910/devops-assessment:"v${GITHUB_RUN_NUMBER}"
          
          docker tag 4568910/devops-assessment:latest-2 4568910/devops-assessment:latest

      - name: Push Docker image
        run: |
          docker push 4568910/devops-assessment:"v${GITHUB_RUN_NUMBER}"
          docker push 4568910/devops-assessment:latest

      