name: Configure Database

on:
  workflow_dispatch:
    inputs:
      db-ip:
        type: string
        description: "Enter the public ip of the databse server"
        required: true
      

jobs:
  run-playbooks:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ansible

    steps: 
      - uses: actions/checkout@v3
        with:
          submodules: true
          # token: ${{secrets.REPO_TOKEN}}

      - name: Setup ssh
        shell: bash 
        run: |
          service ssh status
          eval `ssh-agent -s`
          mkdir -p /home/runner/.ssh/
          touch /home/runner/.ssh/id_rsa
          echo -e "${{secrets.VM_PRIV_KEY}}" > /home/runner/.ssh/id_rsa
          chmod 700 /home/runner/.ssh/id_rsa
          ssh-keyscan -t rsa,dsa,ecdsa,ed25519 ${{ inputs.db-ip }} >> /home/runner/.ssh/known_hosts

      - name: Configure Host host-inventory
        run: |
          cat <<EOF > host-inventory
          [postgres]
          ${{ inputs.db-ip }}
          EOF


      - name: Run ansible script
        shell: bash 
        run: |
          ansible-playbook --private-key /home/runner/.ssh/id_rsa -u ${{secrets.ANSIBLE_DEPLOY_USER}} -u saitama db.yaml


          
