name: Terraform plan
on:
  workflow_dispatch:
    
  push:
    branches:
      - dev

jobs:
  tf-plan:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VERSION: 1.3.6

    defaults:
      run:
        working-directory: terraform
      
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform fmt and init
        run: |
          terraform fmt
          terraform init
          terraform validate

      - name: Terraform plan
        run: |
          terraform plan -var "connection_string=${{ secrets.DATABASE_URL }}" \
          -var "docker_registry_password=${{ secrets.DOCKER_PASSWORD }}" \
          -var "vm-pub-key=${{ secrets.VM_PUB_KEY }}"